# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: czechteacher.net
email: info@czechteacher.net
description: > # this means to ignore newlines until "baseurl:"
    Czech? Do you mean Chechnya? Wait… no Asia?
    Middle Europe, you say? Oh, I see, you mean Czechoslovakia!
    Separated? Never mind.
    And do you even have an educational system there?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://czechteacher.net" # the base hostname & protocol for your site, e.g. http://example.com

disqus_shortname: czechteacher-net
google_analytics: UA-93030737-1


# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

exclude: [vendor]
sass:
  sass_dir: assets/scss
  style: compressed

# Defaults settings
defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
    values:
      layout: "post" # overrides previous default layout
